CREATE TABLE "character" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "birth_year" int,
  "death_year" int,
  "birth_place_id" bigint,
  "death_place_id" bigint,
  "bestiary_id" bigint NOT NULL,
  "gender" "ENUM(homme,femme)",
  "status" "ENUM(vivant,mort,inconnue)",
  "description" TEXT
);

CREATE TABLE "character_objet" (
  "character_id" BIGINT NOT NULL,
  "objet_id" BIGINT NOT NULL,
  "PRIMARY" "KEY(character_id,objet_id)"
);

CREATE TABLE "character_source" (
  "character_id" BIGINT NOT NULL,
  "source_id" BIGINT NOT NULL,
  "PRIMARY" "KEY(character_id,source_id)"
);

CREATE TABLE "quote" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "character_id" BIGINT,
  "text" TEXT NOT NULL,
  "source_id" BIGINT
);

CREATE TABLE "bestiary" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "bestiary_type_id" BIGINT,
  "description" TEXT NOT NULL,
  "character_id" bigint
);

CREATE TABLE "bestiary_type" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "parent_id" BIGINT
);

CREATE TABLE "environment" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL
);

CREATE TABLE "bestiary_environment" (
  "bestiary_id" bigint NOT NULL,
  "environment_id" bigint NOT NULL
);

CREATE TABLE "organisation" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "description" TEXT,
  "organisation_type_id" BIGINT
);

CREATE TABLE "organisation_type" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL
);

CREATE TABLE "geography" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "description" TEXT,
  "type" TEXT,
  "type_id" BIGINT,
  "parent_id" bigint
);

CREATE TABLE "geography_type" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR UNIQUE NOT NULL,
  "description" text
);

CREATE TABLE "source" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" VARCHAR NOT NULL,
  "type" "ENUM(Livre,Jeux,comics,autre)",
  "release_year" INT
);

CREATE TABLE "character_relationship" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "character1_id" BIGINT UNIQUE,
  "character2_id" BIGINT UNIQUE,
  "relationship_type" bigint UNIQUE NOT NULL
);

CREATE TABLE "profession_organisation" (
  "profession_id" BIGINT NOT NULL,
  "organisation_id" BIGINT NOT NULL,
  "PRIMARY" "KEY(profession_id,organisation_id)"
);

CREATE TABLE "relationship_type" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR UNIQUE NOT NULL
);

CREATE TABLE "weakness" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" enum(argent,poison)
);

CREATE TABLE "character_weakness" (
  "character_id" BIGINT NOT NULL,
  "weakness_id" BIGINT NOT NULL,
  "PRIMARY" "KEY(character_id,weakness_id)"
);

CREATE TABLE "bestiary_weakness" (
  "creature_id" BIGINT,
  "weakness_id" BIGINT
);

CREATE TABLE "bestiary_source" (
  "bestiary_id" BIGINT NOT NULL,
  "source_id" BIGINT NOT NULL,
  "PRIMARY" "KEY(bestiary_id,source_id)"
);

CREATE TABLE "organisation_source" (
  "organisation_id" BIGINT NOT NULL,
  "source_id" BIGINT NOT NULL,
  "PRIMARY" "KEY(organisation_id,source_id)"
);

CREATE TABLE "event_source" (
  "event_id" BIGINT NOT NULL,
  "source_id" BIGINT NOT NULL,
  "PRIMARY" "KEY(event_id,source_id)"
);

CREATE TABLE "profession" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "description" TEXT
);

CREATE TABLE "objet" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "description" text,
  "source_id" bigint,
  "character_id" bigint,
  "type" enum(objet-magique,bombe,herbe,potion,bateau,arme,armure)
);

CREATE TABLE "culture" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "description" text
);

CREATE TABLE "culture_element" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "culture_id" BIGINT NOT NULL,
  "element_type" "ENUM(religion,language,money,loisir,magie)",
  "element_id" BIGINT NOT NULL
);

CREATE TABLE "event" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "description" TEXT,
  "year" INT,
  "geography_id" BIGINT,
  "source_id" bigint
);

CREATE TABLE "religion" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "description" text
);

CREATE TABLE "money" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "description" text
);

CREATE TABLE "language" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "description" text
);

CREATE TABLE "loisir" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "description" text
);

CREATE TABLE "magie" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "description" text,
  "type" "enum(sort, signe de sorceleur)",
  "origine" VARCHAR,
  "niveau_requis" VARCHAR
);

CREATE TABLE "sort" (
  "id" bigint NOT NULL,
  "magie_id" BIGINT NOT NULL,
  "name" VARCHAR NOT NULL,
  "description" text,
  "incantation" text,
  "ecole" VARCHAR
);

CREATE TABLE "magie_user" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "character_id" BIGINT,
  "bestiary_id" BIGINT,
  "magie_id" BIGINT
);

CREATE TABLE "sort_user" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "character_id" BIGINT,
  "bestiary_id" BIGINT,
  "sort_id" BIGINT
);

CREATE TABLE "character_profession" (
  "character_id" BIGINT,
  "profession_id" BIGINT,
  "PRIMARY" "KEY(character_id,profession_id)"
);

CREATE TABLE "character_organisation" (
  "character_id" BIGINT,
  "organisation_id" BIGINT,
  "role" VARCHAR,
  "PRIMARY" "KEY(character_id,organisation_id)"
);

CREATE TABLE "geography_money" (
  "geography_id" BIGINT NOT NULL,
  "money_id" BIGINT NOT NULL,
  "PRIMARY" "KEY(geography_id,money_id)"
);

CREATE TABLE "geography_language" (
  "geography_id" BIGINT NOT NULL,
  "language_id" BIGINT NOT NULL,
  "PRIMARY" "KEY(geography_id,language_id)"
);

CREATE TABLE "event_geography" (
  "event_id" BIGINT NOT NULL,
  "geography_id" BIGINT NOT NULL,
  "PRIMARY" "KEY(event_id,geography_id)"
);

CREATE TABLE "geography_religion" (
  "geography_id" BIGINT NOT NULL,
  "religion_id" BIGINT NOT NULL,
  "PRIMARY" "KEY(geography_id,religion_id)"
);

ALTER TABLE "character_objet" ADD FOREIGN KEY ("character_id") REFERENCES "character" ("id");

ALTER TABLE "character_objet" ADD FOREIGN KEY ("objet_id") REFERENCES "objet" ("id");

ALTER TABLE "character_source" ADD FOREIGN KEY ("character_id") REFERENCES "character" ("id");

ALTER TABLE "character_source" ADD FOREIGN KEY ("source_id") REFERENCES "source" ("id");

ALTER TABLE "quote" ADD FOREIGN KEY ("character_id") REFERENCES "character" ("id");

ALTER TABLE "quote" ADD FOREIGN KEY ("source_id") REFERENCES "source" ("id");

ALTER TABLE "profession_organisation" ADD FOREIGN KEY ("profession_id") REFERENCES "profession" ("id");

ALTER TABLE "profession_organisation" ADD FOREIGN KEY ("organisation_id") REFERENCES "organisation" ("id");

ALTER TABLE "character_weakness" ADD FOREIGN KEY ("character_id") REFERENCES "character" ("id");

ALTER TABLE "character_weakness" ADD FOREIGN KEY ("weakness_id") REFERENCES "weakness" ("id");

ALTER TABLE "bestiary_source" ADD FOREIGN KEY ("bestiary_id") REFERENCES "bestiary" ("id");

ALTER TABLE "bestiary_source" ADD FOREIGN KEY ("source_id") REFERENCES "source" ("id");

ALTER TABLE "organisation_source" ADD FOREIGN KEY ("organisation_id") REFERENCES "organisation" ("id");

ALTER TABLE "organisation_source" ADD FOREIGN KEY ("source_id") REFERENCES "source" ("id");

ALTER TABLE "event_source" ADD FOREIGN KEY ("event_id") REFERENCES "event" ("id");

ALTER TABLE "event_source" ADD FOREIGN KEY ("source_id") REFERENCES "source" ("id");

ALTER TABLE "sort" ADD FOREIGN KEY ("magie_id") REFERENCES "magie" ("id");

ALTER TABLE "magie_user" ADD FOREIGN KEY ("magie_id") REFERENCES "magie" ("id");

ALTER TABLE "sort_user" ADD FOREIGN KEY ("sort_id") REFERENCES "sort" ("id");

ALTER TABLE "character_profession" ADD FOREIGN KEY ("character_id") REFERENCES "character" ("id");

ALTER TABLE "character_profession" ADD FOREIGN KEY ("profession_id") REFERENCES "profession" ("id");

ALTER TABLE "character_organisation" ADD FOREIGN KEY ("character_id") REFERENCES "character" ("id");

ALTER TABLE "character_organisation" ADD FOREIGN KEY ("organisation_id") REFERENCES "organisation" ("id");

ALTER TABLE "geography_money" ADD FOREIGN KEY ("geography_id") REFERENCES "geography" ("id");

ALTER TABLE "geography_money" ADD FOREIGN KEY ("money_id") REFERENCES "money" ("id");

ALTER TABLE "geography_language" ADD FOREIGN KEY ("geography_id") REFERENCES "geography" ("id");

ALTER TABLE "geography_language" ADD FOREIGN KEY ("language_id") REFERENCES "language" ("id");

ALTER TABLE "event_geography" ADD FOREIGN KEY ("event_id") REFERENCES "event" ("id");

ALTER TABLE "event_geography" ADD FOREIGN KEY ("geography_id") REFERENCES "geography" ("id");

ALTER TABLE "geography_religion" ADD FOREIGN KEY ("geography_id") REFERENCES "geography" ("id");

ALTER TABLE "geography_religion" ADD FOREIGN KEY ("religion_id") REFERENCES "religion" ("id");

ALTER TABLE "bestiary" ADD FOREIGN KEY ("bestiary_type_id") REFERENCES "bestiary_type" ("id");

ALTER TABLE "bestiary_type" ADD FOREIGN KEY ("parent_id") REFERENCES "bestiary_type" ("id");

ALTER TABLE "bestiary_environment" ADD FOREIGN KEY ("bestiary_id") REFERENCES "bestiary" ("id");

ALTER TABLE "bestiary_environment" ADD FOREIGN KEY ("environment_id") REFERENCES "environment" ("id");

ALTER TABLE "geography" ADD FOREIGN KEY ("type_id") REFERENCES "geography_type" ("id");

ALTER TABLE "geography" ADD FOREIGN KEY ("parent_id") REFERENCES "geography" ("id");

ALTER TABLE "character_relationship" ADD FOREIGN KEY ("character1_id") REFERENCES "character" ("id");

ALTER TABLE "character_relationship" ADD FOREIGN KEY ("character2_id") REFERENCES "character" ("id");

ALTER TABLE "character_relationship" ADD FOREIGN KEY ("relationship_type") REFERENCES "relationship_type" ("id");

ALTER TABLE "bestiary_weakness" ADD FOREIGN KEY ("creature_id") REFERENCES "bestiary" ("id");

ALTER TABLE "bestiary_weakness" ADD FOREIGN KEY ("weakness_id") REFERENCES "weakness" ("id");

ALTER TABLE "culture_element" ADD FOREIGN KEY ("culture_id") REFERENCES "culture" ("id");

ALTER TABLE "character" ADD FOREIGN KEY ("bestiary_id") REFERENCES "bestiary" ("id");

ALTER TABLE "character" ADD FOREIGN KEY ("birth_place_id") REFERENCES "geography" ("id");

ALTER TABLE "character" ADD FOREIGN KEY ("death_place_id") REFERENCES "geography" ("id");

ALTER TABLE "culture_element" ADD FOREIGN KEY ("element_id") REFERENCES "religion" ("id");

ALTER TABLE "culture_element" ADD FOREIGN KEY ("element_id") REFERENCES "language" ("id");

ALTER TABLE "culture_element" ADD FOREIGN KEY ("element_id") REFERENCES "money" ("id");

ALTER TABLE "culture_element" ADD FOREIGN KEY ("element_id") REFERENCES "loisir" ("id");

ALTER TABLE "culture_element" ADD FOREIGN KEY ("element_id") REFERENCES "magie" ("id");

ALTER TABLE "culture_element" ADD FOREIGN KEY ("element_id") REFERENCES "event" ("id");

ALTER TABLE "event" ADD FOREIGN KEY ("source_id") REFERENCES "source" ("id");

ALTER TABLE "objet" ADD FOREIGN KEY ("source_id") REFERENCES "source" ("id");

ALTER TABLE "objet" ADD FOREIGN KEY ("character_id") REFERENCES "character" ("id");

ALTER TABLE "organisation" ADD FOREIGN KEY ("organisation_type_id") REFERENCES "organisation_type" ("id");
