-- -----------------------------
-- Inserts Relation Types
-- -----------------------------
INSERT INTO relation_types (name) 
VALUES
('Alliés', 'Ennemies', 'En bordure de', 'Partenaire économique')
ON CONFLICT (name) DO NOTHING;

-- -----------------------------
-- Inserts Places
-- -----------------------------
-- ==================== Univers (Racine) ====================
-- NOTE : penser à rajouter image_url
INSERT INTO places (id, title, type_place, description, parent_id)
VALUES
(1, 'Univers','univers','Les différents mondes de cette univers regroupe différentes planètes, plusieurs plan parallèle', NULL)
ON CONFLICT (title) DO NOTHING;

-- ==================== Sphera mundi + autre (1er enfant) ====================
INSERT INTO places (id, title, type_place, description, parent_id)
VALUES
(2, 'Sphera Mundi', 'monde', 'La Sphera mundi est la planète ou se situe les évènements de The Witcher', 1),
(3, 'Les différents plans', 'monde', 'Les différents plan, comme le plan où se loge les démon. Est-ce une planète ou un plan différent ??', 1),
(4, 'Multivers', 'monde', 'Ensemble des mondes se trouvant dans cette univers. S''agit-il plutôt de plan parallèle ?',1)
ON CONFLICT (title) DO NOTHING;

-- ==================== (2ème Niveau place - région) ====================
INSERT INTO places (id, title, type_place, description, parent_id)
VALUES
(5, 'Royaume du Nord', 'region', 'Royaume gouverné par différents roi et renne', 2),
(6, 'Empire Nilfgaardien', 'region', 'Le royaume de Nilfgaard est le plus éténdu connue', 2),
(7, 'Désert de Ddiddiwedht', 'multivers', 'Le Désert de Ddiddiwedht était autrefois peuplé', 4)
ON CONFLICT (title) DO NOTHING;

-- ==================== (3ème Niveau place - royaume) ====================
INSERT INTO places (id, title, type_place, description, parent_id)
VALUES
(8, 'Temeria', 'royaume', 'Un des royaumes du Nord gouverné par Foltest', 5),
(9, 'Aedirn', 'royaume', 'un des royaumes du Nord gouverné par Demavend III', 5),
(10, 'Rivia', 'royaume', 'un des royaumes du Nord gouverné par la reine Meve', 5),
(11, 'Nilfgaard', 'royaume', 'un des plus grand royaumes de son temps, gouverne par l''empereur Emhyr var emreis', 6),
(12, 'Zerrikania', 'royaume', 'Des terres sauvages où son peuple comptent de brave guerrier', NULL)
ON CONFLICT (title) DO NOTHING;

-- ==================== (4ème Niveau place - Ville) ====================
INSERT INTO places (id, title, type_place, description, parent_id)
VALUES
(13, 'Vizima', 'capitale', 'Capitale de la Témérie', 8),
(14, 'Blanchefleur', 'village', 'Village dévasté par la guerre ou geralt y chassa un Griffon royal', 8),
(15, 'Les grottes aux lièvres', 'grotte', 'Grotte en Rivie surnommé comme ça par les paysans', 10)
ON CONFLICT (title) DO NOTHING;

-- ==================== (5ème Niveau place - Lieu appartenant au ville) ====================
(16, 'Quartier du Temple', 'quartier', 'Le soulèvement des non-humains a changé le Temple Quartier de Vizima au-delà de la reconnaissance.', 13),
(17, 'Vieux Vizima', 'village', 'L''Ancien wyzima où se situe l''ancien palais de Foltest', 13)

-- ==================== Table de relation ====================

INSERT INTO places_relations (id, place_id, related_place_id, relation_type_id)
VALUES 
(1, )

	--========================================
	-- ==================== Map interactive ==================
	--========================================

-- CREATE Table map_region (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    name VARCHAR(100) NOT NULL UNIQUE,
--    shape_data GEOMETRY(POLYGON, 0) NOT NULL,
--    place_id BIGINT REFERENCES places(id)
--);

--CREATE Table map_marker (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    name VARCHAR(100) NOT NULL UNIQUE,
--    location GEOMETRY(POINT, 0) NOT NULL,
--    type marker_type NOT NULL DEFAULT 'default',
--    -- DEFAULT 'default' = si tu oublies de préciser le type du marqueur, PostgreSQL mettra 'default' automatiquement
--    place_id BIGINT REFERENCES places(id)
--);
