CREATE EXTENSION IF NOT EXISTS postgis;
-- -----------------------------
-- Table Users
-- -----------------------------

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE
	image_url VARCHAR (500)
);

-- -----------------------------
-- Table Place
-- -----------------------------
CREATE Table places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    title VARCHAR(200) NOT NULL UNIQUE,
    type_place place_enum NOT NULL,
    description TEXT NOT NULL,
    image_url VARCHAR(500),
    parent_id BIGINT REFERENCES places(id) ON DELETE SET NULL
	-- Garde les lieux enfants même si le parent est supprimé
);
-- -----------------------------
-- Enum Place
-- -----------------------------
CREATE TYPE place_enum AS ENUM (
    'royaume', 'foret', 'montagne', 'forteresse', 'village', 'univers',
    'ville', 'duché', 'provinces', 'baronnies', 'principautés', 'region',
    'île', 'rivière', 'mer', 'taverne', 'multivers', 'special',
    'magique', 'ruine', 'capitale', 'port', 'monument', 'marais',
    'lac', 'château', 'manoir', 'temple', 'route', 'marché', 'monde',
    'grotte', 'mine', 'plan', 'tour', 'phare', 'quartier', 'default'
);

CREATE Table relation_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE Table places_relations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL REFERENCES places(id) ON DELETE CASCADE,
    related_place_id BIGINT NOT NULL REFERENCES places(id) ON DELETE CASCADE,
    relation_type_id BIGINT NOT NULL REFERENCES relation_types(id) ON DELETE RESTRICT
    -- ON DELETE RESTRICT = on ne peut pas supprimer un type utilisé
);

-- -----------------------------
-- Table Map_region
-- -----------------------------
CREATE Table map_region (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(100) NOT NULL UNIQUE,
    shape_data GEOMETRY(POLYGON, 0) NOT NULL,
    place_id BIGINT REFERENCES places(id)
);

CREATE Table map_marker (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(100) NOT NULL UNIQUE,
    location GEOMETRY(POINT, 0) NOT NULL,
    type marker_type NOT NULL DEFAULT 'default',
    -- DEFAULT 'default' = si tu oublies de préciser le type du marqueur, PostgreSQL mettra 'default' automatiquement
    place_id BIGINT REFERENCES places(id)
);

CREATE TYPE marker_type AS ENUM (
    'royaume', 'foret', 'montagne', 'forteresse', 'village',
    'ville', 'duché', 'provinces', 'baronnies', 'principautés',
    'île', 'rivière', 'mer', 'taverne', 'special',
    'magique', 'ruine', 'capitale', 'port', 'monument', 'marais',
    'lac', 'château', 'manoir', 'temple', 'route', 'marché',
    'grotte', 'mine', 'plan', 'tour', 'phare', 'default'
);

CREATE Table race_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
	description TEXT,
	citation VARCHAR,
	image_url VARCHAR
    parent_id BIGINT REFERENCES race_types(id) ON DELETE SET NULL
);

CREATE Table races (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(100) NOT NULL UNIQUE,
    race_type_id BIGINT NOT NULL REFERENCES race_types(id),
    description TEXT NOT NULL,
    citation VARCHAR(400),
    image_url VARCHAR(500)
);

CREATE Table race_traits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_id BIGINT NOT NULL REFERENCES races(id) ON DELETE CASCADE,
    trait VARCHAR(200) NOT NULL,
    category VARCHAR(50)
);

CREATE Table organisations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    organisation_type_id BIGINT REFERENCES organisation_types(id) ON DELETE RESTRICT
);

CREATE Table organisation_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL
);

CREATE TABLE descriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL CHECK (
		entity_type IN (
        'character', 'place', 'race', 'organisation', 'region',
        'profession', 'culture', 'univers',
        'royaume', 'foret', 'montagne', 'forteresse', 'village',
        'ville', 'duché', 'provinces', 'baronnies', 'principautés',
        'île', 'rivière', 'mer', 'taverne', 'multivers', 'special',
        'magique', 'ruine', 'capitale', 'port', 'monument', 'marais',
        'lac', 'château', 'manoir', 'temple', 'route', 'marché',
        'grotte', 'mine', 'plan', 'tour', 'phare', 'default'
		)
	),
    entity_id BIGINT NOT NULL,
    title VARCHAR(100),
    content TEXT NOT NULL,
    order_index INT DEFAULT 0,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(entity_type, entity_id, order_index)
);

CREATE Table professions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(100) NOT NULL,
    description TEXT
);

CREATE Table cultures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(150) NOT NULL,
    description TEXT
);

CREATE Table characters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(150) NOT NULL UNIQUE,
    birth_date SMALLINT,
    death_date SMALLINT,
    birth_place_id BIGINT REFERENCES places(id) ON DELETE SET NULL,
    death_place_id BIGINT REFERENCES places(id) ON DELETE SET NULL,
    gender VARCHAR(50),
    -- Pour profession : RESTRICT (on ne peut pas supprimer une profession utilisée)
    profession_id BIGINT NOT NULL REFERENCES professions(id) ON DELETE RESTRICT,
    description TEXT NOT NULL,
    citation VARCHAR(400),
    race_id BIGINT REFERENCES races(id) ON DELETE RESTRICT,
    culture_id BIGINT REFERENCES cultures(id) ON DELETE SET NULL
);

CREATE Table character_organisations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id BIGINT NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
    organisation_id BIGINT NOT NULL REFERENCES organisations(id) ON DELETE CASCADE,
    role VARCHAR(50)
);

-- Penser à ajouter des tables d'association ou un système de hiérarchie pour les tables organisation + culture + (profession)
